### ISSUE TITLE
Missing return in 2.6.4 release and it causes runtime error

### ISSUE THREAD

**Issue by Prurite** [NyanChanMeow/SSRSpeed#101]
A return statement is missing on 2.6.4 release, at ssrspeed/config_parser/shadowsocksr_parsers/parser_basic.py, Line 75

![图片](https://user-images.githubusercontent.com/44775584/76760925-8d019500-67c9-11ea-8ef2-34d2f8ef52f4.png)

Before I fix it it ran like this

![图片](https://user-images.githubusercontent.com/44775584/76761073-b4f0f880-67c9-11ea-8e5e-2459e3241971.png)

**Comment by cangyin** [comment]
already fixed in recent commits.

**Comment by Prurite** [comment]
> 
> 
> already fixed in most recent commits.

So when will the next release come?

**Comment by cangyin** [comment]
Just download current commit in `master` branch. it works fine.

**Comment by NyanChanMeow** [comment]
Already fixed in #100
