### ISSUE TITLE
能否把结果导出成为文本文件，这样好解析

### ISSUE THREAD

**Issue by houxinhong** [NyanChanMeow/SSRSpeed#102]
能否把结果导出成为文本文件，这样好解析

**Comment by cangyin** [comment]
运行结果保存为两种文件，在结果文件夹 `result\` 中。一为图片文件，.png 后缀；二为你所需要的文本格式文件，.json 后缀。

第二种文件中保存了运行产生的所有结果。

以上，希望能帮到您。

**Comment by houxinhong** [comment]
问一下Base64 decode failed.这个问题我不知道是怎么回事，使用的是http://175.24.76.155/els_encode.txt这个订阅地址，

**Comment by cangyin** [comment]
我这边帮你看看怎么回事，你把你的回复删掉。

**Comment by cangyin** [comment]
将这一行代码：
https://github.com/NyanChanMeow/SSRSpeed/blob/7e54f2449c011c7fc1de8c21b44308dceb134818/ssrspeed/utils/b64plus.py#L12
改为：
```python
s = s.replace("-", "+").replace("_", "/").replace('\n', '')
```
即可。

顺带感谢您额外提供的机场名字。记得及时重置订阅。

**Comment by houxinhong** [comment]
除了刚才
那个订阅地址还有其他的dingy地址也搞不起，能不能加我QQ私聊：1361973421
