### ISSUE TITLE
这是windows下用的？还是linux下？

### ISSUE THREAD

**Issue by hmgl** [NyanChanMeow/SSRSpeed#11]
如果是linux，那个发行版无痛通过？

**Comment by NyanChanMeow** [comment]
当前版本对Win友好，Linux兼容性将在后续版本中改善

**Comment by ranwen** [comment]
目前某些地方改炸了 暂时不可用

这个版本应该可用
https://github.com/NyanChanMeow/SSRSpeed/pull/1
(自行使用git进行回退)

然后是ubuntu18.04测试能完美运行 需要python3和pip3支持
因为某些原因需要拷贝一份字体或者自己改源码切换字体(exportResult.py搜索msyh.ttc)(其实 https://github.com/keaituzhe/SSRSpeed 有字体)
需要按照ssr本身的依赖装一部分依赖库(如openssl等)
以及如果使用特殊加密需要装加密的lib(libsodium等) 这部分请自行参照ssr-python安装说明

**Comment by NyanChanMeow** [comment]
@ranwen 所以你赶紧给我pr一份msyh.ttc

**Comment by NyanChanMeow** [comment]
#13
