### ISSUE TITLE
无法测速，所有节点测试速度都低于1，python版本是3.8.5

### ISSUE THREAD

**Issue by GYHiroko** [NyanChanMeow/SSRSpeed#122]
![2020-09-11-17-40-26](https://user-images.githubusercontent.com/23479019/92905430-38786300-f456-11ea-829d-f5f32124e30b.png)
@NyanChanMeow

**Comment by lizenghui** [comment]
我也是，  我看ssrspeed_config.json 里 测试要下载https://download.microsoft.com/download/0/A/F/0AFB5316-3062-494A-AB78-7FB0D4461357/7601.17514.101119-1850_Update_Sp_Wave1-GRMSP1.1_DVD.iso   目前这个文件已经无法访问  不知道是不是这块引起。还没细看。
