### ISSUE TITLE
测速逻辑存在问题

### ISSUE THREAD

**Issue by thomas0612** [NyanChanMeow/SSRSpeed#18]
测速逻辑存在问题
1.在测速的过程中当切换到线路2或者3的时候在SSR的服务器连接统计中仍然可以看到线路1的统计数值再跳动 严重的时候会同时看到三个节点的下载量在增加
2.SSR 服务器菜单中有一个按钮【断开当前服务器所有连接】，每次更换节点的时候应当执行该按钮对对应的功能

**Comment by NyanChanMeow** [comment]
该问题起源于为避免SSR 客户端的问题导致的问题，尚处于实验性修复中，且1中bug测试多次均未复现，请等待修复

**Comment by ranwen** [comment]
是否使用socket测速方式

**Comment by thomas0612** [comment]
> 是否使用socket测速方式

使用的fast模式  改天试一下socket

**Comment by thomas0612** [comment]
建议增加每个节点测速时长，很多节点由于部署的是bbr加速起速度比较慢，还未到达峰值速度测速进程已经结束
