### ISSUE TITLE
测速途中强制退出，代理不会自动关闭

### ISSUE THREAD

**Issue by HeroSixo4** [NyanChanMeow/SSRSpeed#22]
需手动到系统代理设置中关闭代理，不关闭后续测试将报错
`Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接`
以及浏览器无链接

**Comment by NyanChanMeow** [comment]
@HeroSixo4 ShadowsocksR-C#已知bug，请更新Dev

**Comment by HeroSixo4** [comment]
> @HeroSixo4 ShadowsocksR-C#已知bug，请更新Dev

好的，感谢！
