### ISSUE TITLE
【bug反馈】web界面数值排序出错

### ISSUE THREAD

**Issue by northsheep** [NyanChanMeow/SSRSpeed#28]
测速结果中点击“TCP Ping”降序排列后，70多的数值被排到了800多和400多之间。经逐个测试，其余四列也存在类似的“小的数字被排列到两个大数字之间”的bug.

![image](https://user-images.githubusercontent.com/13964012/57547943-4ca7de00-7392-11e9-9afc-e776ddebea64.png)

**Comment by NyanChanMeow** [comment]
@northsheep 这是已知问题，Element UI默认排序算法的问题，以后会重写默认排序算法

**Comment by vnvvnv** [comment]
- - 刚刚点了一下 还真是..

**Comment by northsheep** [comment]
> @northsheep 这是已知问题，Element UI默认排序算法的问题，以后会重写默认排序算法

明白了，我昨天刚用，开发大佬们辛苦了。

**Comment by NyanChanMeow** [comment]
> 
> 
> > @northsheep 这是已知问题，Element UI默认排序算法的问题，以后会重写默认排序算法
> 
> 明白了，我昨天刚用，开发大佬们辛苦了。

该问题已在Web UI 0.3.5中修复，目前该版本已上传，请刷新浏览器缓存使用

**Comment by vnvvnv** [comment]
感谢 大佬更新



------------------ 原始邮件 ------------------
发件人: "NyanChanMeow"<notifications@github.com>; 
发送时间: 2019年5月11日(星期六) 晚上8:07
收件人: "NyanChanMeow/SSRSpeed"<SSRSpeed@noreply.github.com>; 
抄送: "Sivan"<ozeng@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [NyanChanMeow/SSRSpeed] 【bug反馈】web界面数值排序出错 (#28)



  
@northsheep 这是已知问题，Element UI默认排序算法的问题，以后会重写默认排序算法
  
明白了，我昨天刚用，开发大佬们辛苦了。
  
该问题已在Web UI 0.3.5中修复，目前该版本已上传，请刷新浏览器缓存使用
 
&mdash;
