### ISSUE TITLE
Web UI中能否支持一键导出

### ISSUE THREAD

**Issue by lu35548** [NyanChanMeow/SSRSpeed#35]
Web UI中能否支持一键导出成PNG和JSON,能否自定义需要显示的列

另外WEB UI的界面看着真的很舒服,大佬tql!

**Comment by NyanChanMeow** [comment]
@lu35548 - 结果全部导出在根目录下的results文件夹中
 - 自定义列显示暂时没有计划

**Comment by lu35548** [comment]
> @lu35548 - 结果全部导出在根目录下的results文件夹中
> 
> * 自定义列显示暂时没有计划

感谢回复,大佬辛苦了
