### ISSUE TITLE
建议增加批量测速所耗费时间(Time used)记录功能

### ISSUE THREAD

**Issue by wangmingph** [NyanChanMeow/SSRSpeed#37]
非常感谢大佬制作的此款测速软件，大佬辛苦了！
批量测速的结果图表(Result Table)里有测速所耗费的流量(Traffic used)统计记录，大佬能否也添加一个测速所耗费的时间(Time used)统计记录功能呢？

**Comment by NyanChanMeow** [comment]
@wangmingph 已在Todo(咕咕)List中
