### ISSUE TITLE
修改超时判定 & 增加测速时间修改

### ISSUE THREAD

**Issue by Prurite** [NyanChanMeow/SSRSpeed#40]
1. 对部分可用性较差的节点测延迟时，5次超时减慢速度，同时5次有时也不足以判断丢包率，建议将 tcpping 和 googleping 中的超时判定改为如下：
```python
while fac < 3 or ( suc != 0 and fac + suc < 10 ):
    # do something
```

2. 部分节点起速较慢，但待测速节点较多时单节点耗时太长也不好，建议加入对单节点测速时间的配置。

**Comment by NyanChanMeow** [comment]
关于第二点暂无较好的解决方案，且由于部分遗留问题导致添加该项存在困难，故暂时不会加入该项配置
