### ISSUE TITLE
非工作目录下运行出错

### ISSUE THREAD

**Issue by g2grey** [NyanChanMeow/SSRSpeed#43]
版本2.4.10
新版本还没试 但是2.4.10有这个问题

如果当前工作目录与程序目录不符 就没法正常测速

举例
如果我在terminal输入
`python3 ~/downloads/SSRSpeed-2.4.10/main.py`
可以读取订阅链接 但是无法测试 
并且会在我当前的目录下生成 config.json, logs 和 result

如果我先更改目录
`cd ~/downloads/SSRSpeed-2.4.10`
再运行 `python3 main.py`
程序就可以正常运行

建议在你main.py里前面加上
```
abspath = os.path.abspath(__file__)
dir_name = os.path.dirname(abspath)
os.chdir(dir_name)
```
用倒是不影响用哈哈
就是给你说一下

另外谢谢制作这个程序！

**Comment by NyanChanMeow** [comment]
@g2grey 非bug

**Comment by g2grey** [comment]
嗯 不是bug 只是一个小建议。。。
