### ISSUE TITLE
测速的时候显示这样

### ISSUE THREAD

**Issue by ing-37** [NyanChanMeow/SSRSpeed#46]
![81D_R0(Y7KU5FX%@83HGBBS](https://user-images.githubusercontent.com/50428905/60767373-af46fd00-a0e9-11e9-969b-c8ee1f3dcaa5.png)

**Comment by NyanChanMeow** [comment]
@z012356 你这明显是缺少依赖库，请仔细阅读readme

**Comment by z012356** [comment]
好的，谢谢。
