### ISSUE TITLE
请教图片结果如何增加显示ip地址呢，不然相同名字的节点不好区分。

### ISSUE THREAD

**Issue by samtone** [NyanChanMeow/SSRSpeed#48]
请教图片结果如何增加显示ip地址呢，不然相同名字的节点不好区分。

**Comment by NyanChanMeow** [comment]
@samtone 无此功能

**Comment by NyanChanMeow** [comment]
@samtone 相同名字的节点会被过滤

**Comment by samtone** [comment]
> @samtone 相同名字的节点会被过滤

过滤是指跳过不测试？？还是只测试排在最前一个？

**Comment by NyanChanMeow** [comment]
@samtone 仅测试最前的一个

**Comment by samtone** [comment]
> @samtone 仅测试最前的一个

.json 文件是完整的测试结果吧 不会过滤？

**Comment by NyanChanMeow** [comment]
@samtone 测试前就进行了过滤

**Comment by samtone** [comment]
> @samtone 测试前就进行了过滤

呃。。。可以不过滤吗。能实现吗？

**Comment by NyanChanMeow** [comment]
@samtone 暂无此选项；可以选择等待咕咕咕

**Comment by samtone** [comment]
> @samtone 暂无此选项；可以选择等待咕咕咕

好吧，感谢解答了。
