### ISSUE TITLE
Add upload test for speedtest, but upload speed only have 500KB.

### ISSUE THREAD

**Issue by p0we7** [NyanChanMeow/SSRSpeed#55]
Code [2e5b59e](https://github.com/p0we7/SSRSpeed/commit/2e5b59e4a367a34691e124ba783388ce5eddd2e5)

如果不设置 socks5 代理 (注释[这行](https://github.com/p0we7/SSRSpeed/blob/2e5b59e4a367a34691e124ba783388ce5eddd2e5/SSRSpeed/SpeedTest/Methods/SpeedTestMethods.py#L45)) 测速的话速度是正常的，一但设置代理之后就只有500K左右了。
![2019-08-15-01-01-25](https://user-images.githubusercontent.com/8407573/63079981-70bb2280-bf72-11e9-8ec5-1ff74bd1e6a1.png)

**Comment by NyanChanMeow** [comment]
@p0we7 目前处于重构阶段且SpeedtestNet使用的是第三方库，暂无法定位问题
