### ISSUE TITLE
SSRSpeed 被Windows denfender拦截

### ISSUE THREAD

**Issue by mygamebbs** [NyanChanMeow/SSRSpeed#61]
开发者，你好！

问题描述：SSRSpeed被Windows defender拦截，具体信息
```
Trojan:Win32/Occamy.C
SSRSpeed-2.6.1\clients\shadowsocksr-libev\ssr-local.exe
```
我将最新版本压缩包上传到www.virustotal.com，链接：
https://www.virustotal.com/gui/file/18938bf4c84e57c67b2f9194973ae8ea772d3c4bbe5c8e70f0f25c2e7471d324/detection
确认问题来自SSRSpeed引用的ShadowsocksR-libev

请问这是一个误报，还是shadowsocksR-libev存在问题？

**Comment by NyanChanMeow** [comment]
使用Dev分支内的客户端，该分支已修复该问题
