### ISSUE TITLE
在测试某机场v2ray时出现较大偏差？

### ISSUE THREAD

**Issue by FolStone** [NyanChanMeow/SSRSpeed#62]
电信宽带下行300MB
平均速度最佳28Mb的线路，Speedtest测试结果为300MB，V2rayN测速6.72M/s
平均速度最差结果为0的线路，Speedtest测试最高速度300MB，结果为117MB，V2rayN测速6.13M/s，然后使用该线路在油管观看2k视频最低速度2wKb，一段时间以后稳定为4wKb
不晓得是不是SSRSpeed的V2ray测速哪里出了问题
值得一提的是V2rayN测速貌似也有点问题，最高成绩也不会超过7M/s

而且貌似这边单位不太对，或者是我才疏学浅……

**Comment by NyanChanMeow** [comment]
@FolStone - SSRSpeed的速度结果单位为MB/s而并非Mb/s
- 请更新至Dev，先前版本有几率在客户端完全启动前开始测试
