### ISSUE TITLE
请教如何针对油管测速?

### ISSUE THREAD

**Issue by joshatt** [NyanChanMeow/SSRSpeed#63]
我用机场主要就是看油管, 相信很多人也这样. 
对ssrspeed还不了解, 不知道如何针对油管测速?

**Comment by NyanChanMeow** [comment]
@joshatt 无此功能，请使用 shadowsocksr-speed

**Comment by joshatt** [comment]
> @joshatt 无此功能，请使用 shadowsocksr-speed

多谢解答
