### ISSUE TITLE
--use-ssr-cs 客户端参数，无效？无法切换成ssr-cs？

### ISSUE THREAD

**Issue by kyohan789** [NyanChanMeow/SSRSpeed#70]
--use-ssr-cs 客户端参数，无效？无法切换成ssr-cs？
我使用参数，无法切换成shadowsocksr.EXE ,仍然使用的是ss-local.EXE

**Comment by cangyin** [comment]
我找到一处可修改的判断代码，修改完后的确可以使脚本使用 ShadowsocksR-C# 进行测速。
![QQ截图20191024163454](https://user-images.githubusercontent.com/50256182/67468682-81c49600-f67d-11e9-8013-54acb04f86e9.jpg)  
  
**修改位置**
`...\SSRSpeed-2.6.3\ssrspeed\config_parser\config_parser.py`: line 241, 249  
将两处 `serverSubscribe` 改为 `serverSubscribes`
![QQ截图20191024163532](https://user-images.githubusercontent.com/50256182/67468881-e2ec6980-f67d-11e9-9f21-7f7ca52dfdff.jpg)

**Comment by NyanChanMeow** [comment]
> --use-ssr-cs 客户端参数，无效？无法切换成ssr-cs？
> 我使用参数，无法切换成shadowsocksr.EXE ,仍然使用的是ss-local.EXE

未复现，该功能仅支持 SSR 订阅使用，若识别为非 SSR 将会忽略该参数

**Comment by cangyin** [comment]
我在 Windows 上使用命令
`main.py -c ...\path\to\ssr-gui-config\file --use-ssr-cs` 运行工具。的确出现了脚本仍然启动 ShadowsocksR-libev 作为测速客户端的情况。修改前述语句后被启动的测速客户端为 ShadowsocksR-C#

**Comment by NyanChanMeow** [comment]
> 我在 Windows 上使用命令
> `main.py -c ...\path\to\ssr-gui-config\file --use-ssr-cs` 运行工具。的确出现了脚本仍然启动 ShadowsocksR-libev 作为测速客户端的情况。修改前述语句后被启动的测速客户端为 ShadowsocksR-C#

已确认为配置文件类型误判，已修复
