### ISSUE TITLE
Error: No config

### ISSUE THREAD

**Issue by callzhang** [NyanChanMeow/SSRSpeed#74]
尝试使用web版，表示config文件失败，"Error: No config"
没找到说明，请问如何使用？

![image](https://user-images.githubusercontent.com/5102827/68546521-064f3c80-0412-11ea-9ee2-b5069f93a028.png)

**Comment by NyanChanMeow** [comment]
请提供详细信息

**Comment by callzhang** [comment]
1. 在terminal键入：`python3 web.py`
2. 在页面输入订阅地址，并点击“read”
3. 设置“test method”和“test mode”
4. 点击“Start”
5. 界面弹出“Error No config”
如图：
![image](https://user-images.githubusercontent.com/5102827/68738789-2b19fe80-0622-11ea-8aac-bfb3793e4ee4.png)

**Comment by NyanChanMeow** [comment]
从图片来看，你没有在节点列表选择待测节点

**Comment by callzhang** [comment]
> 从图片来看，你没有在节点列表选择待测节点

天呐。这个错误提示也太魔幻了。thx

**Comment by NyanChanMeow** [comment]
会在下个版本优化相关输出，感谢反馈
