### ISSUE TITLE
全节点无速度

### ISSUE THREAD

**Issue by YouHaveGone** [NyanChanMeow/SSRSpeed#82]
![image](https://user-images.githubusercontent.com/36957938/71544869-24233180-29bf-11ea-845b-a632188f65ac.png)

**Comment by bickman** [comment]
换一种连接方式，应该就有了

**Comment by 81981266** [comment]
我也是全节点没速度……

**Comment by cangyin** [comment]
建议用命令行方式试试，看看出问题在哪里。
