### ISSUE TITLE
观察运行log，发现经常get不到正确的ip位置信息（city显示unknown）

### ISSUE THREAD

**Issue by kingofotaku** [NyanChanMeow/SSRSpeed#85]
一开始以为是获取信息的api有问题，后来手动访问了一下发现没问题，不知可否优化一下？

**Comment by NyanChanMeow** [comment]
是否可以提供示例的信息，IP可打码

**Comment by kingofotaku** [comment]
大概就是这么个情况 不过今天跑了一下又发现基本都能get到了 很迷


![20200123120453](https://user-images.githubusercontent.com/12953574/72956715-b8748e80-3ddb-11ea-8cec-fc6de62c88e4.png)

另外我发现获取失败的节点都是timeout的 难道这个api只能判断连得上的节点？

**Comment by NyanChanMeow** [comment]
如果连接到 `https://api.ip.sb` 超时的话，将无法获取IP信息；如果节点本身超时，则不会通过节点获取IP信息

**Comment by kingofotaku** [comment]
> 如果连接到 `https://api.ip.sb` 超时的话，将无法获取IP信息；如果节点本身超时，则不会通过节点获取IP信息

那有可能上次是我自己网络不太好，连不上获取ip的地址
