### ISSUE TITLE
请教参数“-C”的用法

### ISSUE THREAD

**Issue by ausers** [NyanChanMeow/SSRSpeed#87]
`  -C RESULT_COLOR, --color=RESULT_COLOR
                    Set the colors when exporting images..`
这个参数没有看到使用示例，网上也没看到相关说明，问了些人都是用改配置文件的方式，自己尝试了几次都不成功，所以希望知道具体使用方式。

顺便想确定下v2ray-core最少需要存在哪几个文件？

**Comment by NyanChanMeow** [comment]
1. 可以参考配置文件内的颜色的命名，如 `origin`，使用 `-C` 指定名称可以使用特定的配色方案输出图片
2. 至少需要 `v2ctl` 和 `v2ray` 这两个文件，以确保 V2Ray 的正常运行

**Comment by ausers** [comment]
> 1. 可以参考配置文件内的颜色的命名，如 `origin`，使用 `-C` 指定名称可以使用特定的配色方案输出图片
> 2. 至少需要 `v2ctl` 和 `v2ray` 这两个文件，以确保 V2Ray 的正常运行

理解了，感谢。

**Comment by ausers** [comment]
> 1. 可以参考配置文件内的颜色的命名，如 `origin`，使用 `-C` 指定名称可以使用特定的配色方案输出图片
> 2. 至少需要 `v2ctl` 和 `v2ray` 这两个文件，以确保 V2Ray 的正常运行

为了懒得记命令弄了个批处理用，我觉得还是挺好用的2333~
[ssrspeed一键.bat](https://ausers.github.io/files/ssrspeed一键.bat)
