### ISSUE TITLE
Your system does not supported.

### ISSUE THREAD

**Issue by Kawaii-KM** [NyanChanMeow/SSRSpeed#88]
```
(Flask) MBA:SSRSpeed-2.6.4 kevinma$ python3 web.py 
Your system does not supported.Please contact developer.
```
macOS 10.13.6
看不懂
非得这么做吗？

**Comment by Kawaii-KM** [comment]
通过配置虚拟环境，我的确可以在macOS上使用SSRSpeed

**Comment by Kawaii-KM** [comment]
`MBA:~ root# python3
Python 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
`
`>>> import platform
>>> platform.platform()
'macOS-10.13.6-x86_64-i386-64bit'
`

**Comment by NyanChanMeow** [comment]
感谢反馈，将在下一版本优化

**Comment by cfm1120** [comment]
python web.py
Your system does not supported.Please contact developer.
提示这个
@Kawaii-KM 用你的方法也不行，python2.7我早就删掉了

Python 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.platform()
'macOS-10.14.6-x86_64-i386-64bit'
