### ISSUE TITLE
节点过滤问题

### ISSUE THREAD

**Issue by ausers** [NyanChanMeow/SSRSpeed#89]
节点IP相同时，会导致读取订阅时节点被过滤，希望能在后续更新中解决，当前使用版本2.6.4，在2.6.3中也发现同样问题
但webUI就不会过滤
![QQ截图20200208001928](https://user-images.githubusercontent.com/54773815/74046312-45892b80-4a09-11ea-850e-a5a8ad36f24c.png)
![QQ截图20200208002332](https://user-images.githubusercontent.com/54773815/74046321-49b54900-4a09-11ea-969b-1dd6ccfb46ef.png)

与 #48 应该是类似过滤问题

**Comment by cangyin** [comment]
参看这一代码段：
https://github.com/NyanChanMeow/SSRSpeed/blob/89928e2f9c74df5953dbd417be89192f5ca5fc7c/ssrspeed/config_parser/base_parser.py#L57-L64

服务器IP、端口都相同的节点才会被过滤。因为服务器IP、端口都相同的节点本就是同一节点。

**Comment by ausers** [comment]
> 参看这一段代码：
> https://github.com/NyanChanMeow/SSRSpeed/blob/89928e2f9c74df5953dbd417be89192f5ca5fc7c/ssrspeed/config_parser/base_parser.py#L57-L64
> 
> 服务器IP、端口都相同的节点才会被过滤。因为服务器IP、端口都相同的节点本就是同一节点。

![QQ截图20200315170003](https://user-images.githubusercontent.com/54773815/76698511-b42f6800-66de-11ea-9c46-49a41608c13f.png)
以我用的这家CDN中转机场为例，入口可以设置全部统一，但出口IP各自不同
![QQ截图20200315170426](https://user-images.githubusercontent.com/54773815/76698539-2738de80-66df-11ea-9a80-21d9cb3e8c2b.png)
![QQ截图20200315170506](https://user-images.githubusercontent.com/54773815/76698541-299b3880-66df-11ea-90ca-f43b49ca70a5.png)
如图为webui截图，为方便我只pingonly了头两个节点，但足够说明了

**Comment by cangyin** [comment]
IP、端口相同的地址，怎么分成了多个节点呢，这有点超出我的理解范围。原谅我对这一点并不了解。

**这个问题应该可以这样解决：**

将此函数
https://github.com/NyanChanMeow/SSRSpeed/blob/89928e2f9c74df5953dbd417be89192f5ca5fc7c/ssrspeed/config_parser/base_parser.py#L50-L67

改成：
```python
    def __checkInList(self,item,_list): 
        return False
```
_注意在修改文件之前进行备份_

**Comment by ausers** [comment]
> IP、端口相同的地址，怎么分成了多个节点呢，这有点超出我的理解范围。原谅我对这一点并不了解。
> 
> **这个问题应该可以这样解决：**
> 
> 将此函数
> https://github.com/NyanChanMeow/SSRSpeed/blob/89928e2f9c74df5953dbd417be89192f5ca5fc7c/ssrspeed/config_parser/base_parser.py#L50-L67
> 
> 改成：
> 
> ```python
>     def __checkInList(self,item,_list): 
>         return False
> ```
> 
> _注意在修改文件之前进行备份_

节点是v2ray，看了下节点信息，应该是通过ws域名加以区分（我也不懂，但节点其他部分完全相同，那就只有这里了）
另外感谢您的帮助

**Comment by ausers** [comment]
> IP、端口相同的地址，怎么分成了多个节点呢，这有点超出我的理解范围。原谅我对这一点并不了解。
> 
> **这个问题应该可以这样解决：**
> 
> 将此函数
> https://github.com/NyanChanMeow/SSRSpeed/blob/89928e2f9c74df5953dbd417be89192f5ca5fc7c/ssrspeed/config_parser/base_parser.py#L50-L67
> 
> 改成：
> 
> ```python
>     def __checkInList(self,item,_list): 
>         return False
> ```
> 
> _注意在修改文件之前进行备份_

经尝试，仅修改此函数无法解决，另外__checkInList一共出现了7次，没学过相关知识不清楚如何修改
![QQ截图20200315194213](https://user-images.githubusercontent.com/54773815/76700747-84d82580-66f5-11ea-9cef-326836b8a13f.png)

**Comment by cangyin** [comment]
https://github.com/cangyin/SSRSpeed

**Comment by ausers** [comment]
> 我看漏了， 还有一处函数：
> https://github.com/NyanChanMeow/SSRSpeed/blob/89928e2f9c74df5953dbd417be89192f5ca5fc7c/ssrspeed/config_parser/node_filters.py#L28
> 
> 这个是已经修改的临时版本，你看看有没有用。
> https://github.com/cangyin/SSRSpeed/tree/allow_dup_nodes

感谢，可行
