### ISSUE TITLE
Termux  下 multidict 无法安装

### ISSUE THREAD

**Issue by 821938089** [NyanChanMeow/SSRSpeed#92]
running build_ext
  building 'multidict._multidict' extension
  creating build/temp.linux-aarch64-3.7
  creating build/temp.linux-aarch64-3.7/multidict
  aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Oz -Oz -fPIC -I/data/data/com.termux/files/usr/include/python3.7m -c multidict/_multidict.c -o build/temp.linux-aarch64-3.7/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
  multidict/_multidict.c:1:10: fatal error: 'Python.h' file not found
  #include "Python.h"
           ^~~~~~~~~~
  1 error generated.
  error: command 'aarch64-linux-android-clang' failed with exit status 1

  ----------------------------------------
  Failed building wheel for multidict
  Running setup.py clean for multidict
Failed to build multidict
Could not build wheels for multidict which use PEP 517 and cannot be installed directly

**Comment by walwan** [comment]
可以尝试升级termux与python之最新版本。
我使用termux 0.92, python/stable,now 3.8.1-4 aarch64 [installed], 在/data/data/com.termux/files/usr/include/python3.8/目录下有python.h文件。
