### ISSUE TITLE
请求 命令不分大小写

### ISSUE THREAD

**Issue by freehehe** [NyanChanMeow/SSRSpeed#97]
[2020-03-11 00:08:25,799][INFO][10008][ssrspeed_core.py:165]35 node(s) will be test.
Before the test please confirm the nodes,Ctrl-C to exit. (Y/N)
 这一步的yn能不能不区分大小写，或者说明一下，再或者默认回车yes
我卡在这半个小时
：O

**Comment by cangyin** [comment]
你可以将这一行
https://github.com/NyanChanMeow/SSRSpeed/blob/89928e2f9c74df5953dbd417be89192f5ca5fc7c/main.py#L243

改成如下：
```python
    if (ans.upper() == "Y"):
```

即可使大小写均通过确认操作。

但我个人并不建议这样做，因为这一步确认操作的本意就是让您谨慎做出选择，而不是”很方便地下一步“。

以上。

**Comment by cangyin** [comment]
如果你觉得命令行操作方式太不合习惯的话，建议使用 web.py （网页交互方式）
